version: "3.8"

services:
    apis-ref:
        build:
            context: ./apis-ref
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        restart: always
        volumes:
            - logapps:/var/log/apps
        container_name: apis-ref
        hostname: apis-ref

    apis-ad:
        build:
            context: ./apis-ad
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        volumes:
            - logapps:/var/log/apps
        restart: always
        container_name: apis-ad
        hostname: apis-ad

    apis-lol:
        build:
            context: ./apis-lol
            dockerfile: Dockerfile
        ports:
            - "8085:8085"
        volumes:
            - logapps:/var/log/apps
        container_name: apis-lol
        restart: always
        hostname: apis-lol

    apis-google:
        build:
            context: ./apis-google
            dockerfile: Dockerfile
        ports:
            - "8084:8084"
        volumes:
            - logapps:/var/log/apps
        restart: always
        container_name: apis-google
        hostname: apis-google

    apis-pca:
        build:
            context: ./apis-pca
            dockerfile: Dockerfile
        ports:
            - "8086:8086"
        restart: always
        volumes:
            - logapps:/var/log/apps
        container_name: apis-pca
        hostname: apis-pca

    apis-sirh:
        build:
            context: ./apis-sirh
            dockerfile: Dockerfile
        ports:
            - "8089:8089"
        restart: always
        volumes:
            - logapps:/var/log/apps
        container_name: apis-sirh
        hostname: apis-sirh

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
            - 443:443
        restart: always
        volumes:
            - lognginx:/etc/nginx/log
        container_name: nginx
        hostname: nginx

    tomcat-arlg:
        build:
            context: ./tomcat-arlg
            dockerfile: Dockerfile
        ports:
            - "40081:8080"
        restart: always
        user: root
        volumes:
            - logapps-arlg:/usr/local/tomcat/logs
            - webapps-arlg:/usr/local/tomcat/webapps
            - ./tomcat-arlg/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-arlg/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-arlg/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-arlg
        hostname: tomcat-arlg

    tomcat-asgr:
        build:
            context: ./tomcat-asgr
            dockerfile: Dockerfile
        ports:
            - "40082:8080"
        restart: always
        user: root
        volumes:
            - logapps-asgr:/usr/local/tomcat/logs
            - webapps-asgr:/usr/local/tomcat/webapps
            - ./tomcat-asgr/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-asgr/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-asgr/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-asgr
        hostname: tomcat-asgr

    tomcat-acau:
        build:
            context: ./tomcat-acau
            dockerfile: Dockerfile
        ports:
            - "40083:8080"
        restart: always
        user: root
        volumes:
            - logapps-acau:/usr/local/tomcat/logs
            - webapps-acau:/usr/local/tomcat/webapps
            - ./tomcat-acau/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-acau/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-acau/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-acau
        hostname: tomcat-acau

    tomcat-acdc:
        build:
            context: ./tomcat-acdc
            dockerfile: Dockerfile
        ports:
            - "40084:8080"
        restart: always
        user: root
        volumes:
            - logapps-acdc:/usr/local/tomcat/logs
            - webapps-acdc:/usr/local/tomcat/webapps
            - ./tomcat-acdc/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-acdc/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-acdc/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-acdc
        hostname: tomcat-acdc

    tomcat-agpe:
        build:
            context: ./tomcat-agpe
            dockerfile: Dockerfile
        ports:
            - "40085:8080"
        restart: always
        user: root
        volumes:
            - logapps-agpe:/usr/local/tomcat/logs
            - webapps-agpe:/usr/local/tomcat/webapps
            - ./tomcat-agpe/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-agpe/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-agpe/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-agpe
        hostname: tomcat-agpe

    tomcat-apca:
        build:
            context: ./tomcat-apca
            dockerfile: Dockerfile
        ports:
            - "40086:8080"
        restart: always
        user: root
        volumes:
            - logapps-apca:/usr/local/tomcat/logs
            - webapps-apca:/usr/local/tomcat/webapps
            - ./tomcat-apca/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-apca/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-apca/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-apca
        hostname: tomcat-apca

    tomcat-asirh:
        build:
            context: ./tomcat-asirh
            dockerfile: Dockerfile
        ports:
            - "40087:8080"
        restart: always
        user: root
        volumes:
            - logapps-asirh:/usr/local/tomcat/logs
            - webapps-asirh:/usr/local/tomcat/webapps
            - ./tomcat-asirh/resources/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./tomcat-asirh/resources/conf/server.xml:/usr/local/tomcat/conf/server.xml
            - ./tomcat-asirh/resources/conf/logging.properties:/usr/local/tomcat/conf/logging.properties
        container_name: tomcat-asirh
        hostname: tomcat-asirh

volumes:
    logapps:
        driver_opts:
            type: none
            device: /var/log/apps/
            o: bind
    lognginx:
        driver_opts:
            type: none
            device: /var/log/nginx/
            o: bind
    logapps-arlg:
        driver_opts:
            type: none
            device: /var/log/apps/arlg/
            o: bind
    webapps-arlg:
        driver_opts:
            type: none
            device: /opt/apps/webapps/arlg/
            o: bind
    logapps-apca:
        driver_opts:
            type: none
            device: /var/log/apps/apca/
            o: bind
    webapps-apca:
        driver_opts:
            type: none
            device: /opt/apps/webapps/apca/
            o: bind
    logapps-asgr:
        driver_opts:
            type: none
            device: /var/log/apps/asgr/
            o: bind
    webapps-asgr:
        driver_opts:
            type: none
            device: /opt/apps/webapps/asgr/
            o: bind
    logapps-acau:
        driver_opts:
            type: none
            device: /var/log/apps/acau/
            o: bind
    webapps-acau:
        driver_opts:
            type: none
            device: /opt/apps/webapps/acau/
            o: bind
    logapps-acdc:
        driver_opts:
            type: none
            device: /var/log/apps/acdc/
            o: bind
    webapps-acdc:
        driver_opts:
            type: none
            device: /opt/apps/webapps/acdc/
            o: bind
    logapps-agpe:
        driver_opts:
            type: none
            device: /var/log/apps/agpe/
            o: bind
    webapps-agpe:
        driver_opts:
            type: none
            device: /opt/apps/webapps/agpe/
            o: bind
    logapps-asirh:
        driver_opts:
            type: none
            device: /var/log/apps/asirh/
            o: bind
    webapps-asirh:
        driver_opts:
            type: none
            device: /opt/apps/webapps/asirh/
            o: bind
